title: Martin Allen
photo: /assets/img/headshot.jpeg
description: Professional Page
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
resume: ./assets/pdf/resume.pdf
github:
  is_user_page: true
  owner_url: https://github.com/martyall
